#ifndef __ITGOP_VERSION_H__
#define __ITGOP_VERSION_H__

// Generated by ResEdit, dunno what this does.
#ifdef _WIN32
#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
#endif


// Use macros for version numbers so they can easily be used as strings or numbers as needed.
#define ITGOP_VERSION_MAJOR 2
#define ITGOP_VERSION_MINOR 0
#define ITGOP_VERSION_FIX 0
#define ITGOP_VERSION_REVISION 0

#include <string>
namespace oggpatcher
{
// The string to use for displaying the name of the program (different from the name of the executable).
extern const std::string g_programName;

// The program version string, eg 1.0.0.0
extern const std::string g_programVersionString;

// A message about the copyright and software license information.
extern const std::string g_copyrightMessage;
}

#endif // end include guard

/*
 Copyright 2010 Greg Najda

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
