#ifndef __ITGOP_VERSION_H__
#define __ITGOP_VERSION_H__

// Generated by ResEdit, dunno what this does.
#ifdef _WIN32
#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif
#endif


// Use macros for version numbers so they can easily be used as strings or numbers as needed.
#define ITGOP_VERSION_MAJOR 2
#define ITGOP_VERSION_MINOR 0
#define ITGOP_VERSION_FIX 0
#define ITGOP_VERSION_REVISION $revision$

#include <string>
namespace oggpatcher
{
// The string to use for displaying the name of the program (different from the name of the executable).
extern const std::string g_programName;

// The program version string, eg 1.0.0.0
extern const std::string g_programVersionString;

// A message about the copyright and software license information.
extern const std::string g_copyrightMessage;
}

#endif // end include guard
